### PR TITLE
Folder restructure

### PR DESCRIPTION
**Pull request by maxhealy01**
## Summary
I eliminated the week_x folders and moved all subfolders into the main blind-75 folder. Within each subfolder (ie, Array, String, Hash_Table), I created a new folder for each algorithm. These each contain a test file and a logic file.

Some of the algorithms didn't have tests, so I wrote them. Previous tests were updated to test for more cases.

All of the logic files were updated to include a description of the problem at the top, followed by JSDoc comments describing the variables.

## Thought Process
My initial plan for this repo was to follow the weekly plan for completing the Blind 75 leetcode problems, as described here https://www.techinterviewhandbook.org/best-practice-questions/.

However, as I began to incorporate the Grind 75 tool (https://www.techinterviewhandbook.org/grind75), the idea of using weeks started to seem nonsensical. I was doing problems out of order, and the work flow of submitting algorithms through PRs made such a strict timeline almost meaningless.

I decided that it would be better to arrange the algorithms according to the data structures that they're meant to incorporate. It makes the repo much easier to read and navigate.

On top of this, there was a schism between the expectations of my earlier algorithms and my more recent contributions. Specifically, I started with a massive `Array.test.js` file. I figured that it would be a perfect time to update the previously submitted code to accord with my working standards of folder structure and add JS Docs to files without them.

Overall this PR makes the repo internally consistent, easier to navigate and easier to test.

## Issue
N/A

## Checklist
- [X] Contains JSDoc comments
- [X] Contains tests
- [X] Completed self review

### CODE REVIEW

**Comment by tannaurus** [comment]
Looks great 👍 

Can we be consistent with casing of our file structure? I.e, lowercase everything 😄 

Also, can we add a .gitignore for the node_modules directory? That's a huge directory and should be removed from the repo to improve push/pull response rate.

**Comment by tannaurus** [comment]
As a general note that doesn't need to change anything here:

For MRs that are this large due to moving things around and not really actual code changes, it makes it much easier to review if you hold off on _any_ code changes until after it gets merged; instead of improving documentation, etc, along the way. It's much nicer to see a giant diff like this and have a certain degree of trust that nothing actually changed, instead of having to piece through the mess of red and green to figure out what actually changed 👻

**Comment by maxhealy01** [comment]
> Looks great 👍
> 
> Can we be consistent with casing of our file structure? I.e, lowercase everything 😄
> 
> Also, can we add a .gitignore for the node_modules directory? That's a huge directory and should be removed from the repo to improve push/pull response rate.

I lowercased everything!

Also, I thought that I'd already added node_modules to .gitignore. I'm not seeing node_modules in the "Files changed" tab - are they somewhere else?

**Comment by tannaurus** [comment]
Nice work 👍

**Pull request merged**
